### ISSUE TITLE
Run service in Docker

### ISSUE THREAD

**Issue by kravcs** [wojciechpawlinow/apiports#1]
It would be nice to see the running service in Docker, docker-compose file should be not for demonstration purpose but usage.

**Comment by wojciechpawlinow** [comment]
Yes, indeed. 

However, since you can run that application via `make run` I decided to not spend more time on the less important stuff, which in real life I wouldn't probably need to write from scratch. 

I've wanted to focus more on coding.

**Comment by kravcs** [comment]
We are highly focused on testing our solution in the infrastructure setup and Docker knowledge are essential.

**Comment by wojciechpawlinow** [comment]
I've just quickly pushed the working version.

**Comment by kravcs** [comment]
Currently the size of the Docker image of your app is 1.1 GB. Can you reduce it?

**Comment by wojciechpawlinow** [comment]
Yes, I can definitely make that smaller by using multi stage and alpine image as I do in my projects at work.
I'll do that as soon as possible during the weekend or Monday morning.

**Comment by wojciechpawlinow** [comment]
The Docker image size has been significantly decreased.
