### ISSUE TITLE
Search port functionality

### ISSUE THREAD

**Issue by kravcs** [wojciechpawlinow/apiports#2]
The search port functionality is missing, expected to be found by port id.

**Comment by wojciechpawlinow** [comment]
Thank you for pointing that out. It is a missing feature indeed; however, that search port functionality is out of scope, according to the task description I've gotten from you. 

That shouldn't be too much effort providing that, though.

**Comment by wojciechpawlinow** [comment]
An HTTP server with GET method has been added.
