### ISSUE TITLE
Linter is missing

### ISSUE THREAD

**Issue by kravcs** [wojciechpawlinow/apiports#3]
Linter is missing and expected to be configurable (yaml).

**Comment by wojciechpawlinow** [comment]
Please have a look at all the details in the README file. I want to highlight that I've provided a `revive` - a _fast, configurable, extensible, flexible, and beautiful linter for Go_. You might want to check out the `defaults.toml` config file at the root level of this project.

**Comment by kravcs** [comment]
I see, however Makefile is missing the command which you described in Readme, so I'm unable to run your linter.

**Comment by wojciechpawlinow** [comment]
Good catch! I've just pushed a change that fixes the issue. After I had named that command `make lint` I forgot to update Makefile service name.
